services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - XDG_CACHE_HOME=/tmp/.cache
    env_file:
      - .env
    volumes:
      - type: bind
        source: /mnt/ceph-videos/YouTube
        target: /mnt/ceph-videos/YouTube
      - ./data:/app/data
      - ./archives:/app/archives
    restart: unless-stopped
